baseURL = "https://emacs.cc/"
languageCode = "en-us"
title = "大道至簡"
theme = "hugo-xmin"
paginate = 30
pygmentsCodeFences = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
footer = "© eggcaker 2020. [冀ICP备2020025756号-1](http://beian.miit.gov.cn/) <br>Powered by [Hugo](https://gohugo.io/), [ox-hugo](https://github.com/kaushalmodi/ox-hugo/) and [Emacs](https://www.gnu.org/software/emacs/)."


[permalinks]
    blog = "/:filename/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
