#+TITLE:      iEmacs 
#+AUTHOR:     eggcaker
#+EMAIL:      eggcaker AT gmail DOT com
#+STARTUP:    align fold nodlcheck hidestars oddeven intestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c)
#+LANGUAGE:   en
#+PRIORITIES: A C B
#+CATEGORY:   iemacs
#+OPTIONS:    H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t TeX:t LaTeX:t skip:nil d:(HIDE) tags:not-in-toc

#+BEGIN_HTML
<script>
  (function() {
    var cx = '002949567369843271026:s8ydninggpy';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:searchbox-only></gcse:searchbox-only>
#+END_HTML


iEmacs [[http://orgmode.org/worg/sitemap.html][sitemap]] and [[http://orgmode.org/worg/theindex.html][index]]

* Introduction to Org-Mode and Worg sssl

[[http://orgmode.org][Org-mode]] is a powerful system for organizing your complex life with
simple plain-text files.  It seamlessly integrates all your notes,
mindmaps, TODO lists, calendar, day planner, and project schedules
into a single system that can be easily searched (e.g. by grep),
encrypted (e.g. by [[http://www.gnupg.org/][GnuPG]]), backed up and synced (e.g.  by Dropbox),
imported/exported, and [[file:org-faq.org::*MobileOrg][accessed on the go]] (e.g. on an iPhone or
Android smartphone).  It can even be used for authoring web pages and
documents.

Check out some [[file:org-screenshots.org][screenshots of Org-mode]] in action.  See [[file:org-quotes.org][what people have to
say]] about Org-mode, and read a few [[file:org-testimonies/index.org][user stories]]!

Org-mode is distributed as part of the popular [[http://www.gnu.org/software/emacs/][Emacs]] text editor and runs
wherever Emacs runs, including on GNU-Linux, Windows, and Mac.  Written by
Carsten Dominik, it is currently maintained by Bastien Guerry and used by
many helpful people who, like you, are desperate to get and stay organized.

The page you're reading is part of =Worg=, a section of the [[http://orgmode.org/][Org-mode web
site]] that is written by a volunteer community of Org-mode fans.  It
includes tutorials, ideas, code snippets, etc., shared to make your
introduction and customization of Org-mode as easy as possible.  Worg is
maintained by Matthew Lundin, a group of [[file:worgers.org][Worg contributors]], and maybe [[file:worg-todo.org][you]].

* Org-Mode Resources
  :PROPERTIES:
  :ID:       A6F83C16-B1B9-405A-B996-8D2CA1274DEB
  :END:

** Learn Org-Mode

#+index: Tutorials
#+index: Glossary

- [[http://orgmode.org/][Org-mode Main Page]]      : The official page for Org-mode
- [[file:org-tutorials/index.org][Org-mode Tutorials]]      : Your best starting point
- [[file:org-glossary.org][Org-mode Glossary]]       : An explanation of org-mode terminology
- [[http://orgmode.org/manual/index.html][Org-mode Manual]] 	  : Extensive and complete documentation
- [[file:org-configs/index.org][Org-mode configuration]]  : Beginner's customization guide, examples, survey,
  and a list of all hooks
- [[file:orgcard.org][Org-mode reference card]] : check the [[file:orgcard.org][HTML]], [[http://orgmode.org/orgcard.pdf][pdf]] and [[http://orgmode.org/orgcard.txt][ASCII]] versions.
  - French translation of the orgcard ([[file:code/latex/fr-orgcard.tex][tex]] - [[file:images/bzg/fr-orgcard.pdf][pdf]])


** Check Out Third-Party Contributions

- [[file:org-contrib/index.org][Contributed packages]], including extensive documentation
- Repository of contributed code:
  1. the =contrib/= directory of the Org-mode package
  2. the [[http://orgmode.org/worg/code/][code]] directory of Worg
     - [[http://orgmode.org/worg/code/org-info-js][org-info-js]] by Sebastian Rose: great javascript
       tool to navigate through a HTML page (as exported by Org) the way you
       navigate through an Org or an info manual, i.e. supporting folding,
       previous/next buttons, etc.
- [[file:org-devel.org][Additions under development]]

# FIXME: should we add this?

# [[file:org-survey.org][Org survey results]]
# [[file:org-code/index.org][Org add-ons]] should be documented here and maybe not in the manual?

* Join the Community

- Check out the list of [[file:worgers.org][Worgers and their User Pages]] and a few
  [[file:org-people.org][profiles of the Org-mode Community]] (with photos ☺)
- Meet other users in the flesh at [[file:orgcamps.org][OrgCamps]]

** Help out

- Improve Worg by sharing your knowledge about Org-mode: see [[Maintenance of Worg]].
- Improve Org-mode:
  - Send [[http://orgmode.org/org.html#Feedback][bug reports]] after checking the [[file:org-issues.org][issue tracker]]
  - Help [[file:org-tests/index.org][test]]
  - [[file:org-contribute.org][Contribute to Org-mode]]

** Latest changes to the Worg git repository

#+begin_html
<script language="JavaScript" src="http://feed2js.org//feed2js.php?src=http%3A%2F%2Forgmode.org%2Fw%2F%3Fp%3Dworg.git%3Ba%3Drss%3Bopt%3D--no-merges&num=10&au=y&date=y&targ=y&utf=y"  charset="UTF-8" type="text/javascript"></script>

<noscript>
<a href="http://feed2js.org//feed2js.php?src=http%3A%2F%2Forgmode.org%2Fw%2F%3Fp%3Dworg.git%3Ba%3Drss%3Bopt%3D--no-merges&num=10&au=y&date=y&targ=y&utf=y&html=y">View RSS feed</a>
</noscript>
#+end_html

Note: You can also subscribe to changes via [[http://orgmode.org/w/?p%3Dworg.git%3Ba%3Drss%3Bopt%3D--no-merges][RSS]] or [[http://orgmode.org/w/?p%3Dworg.git%3Ba%3Datom%3Bopt%3D--no-merges][ATOM]] (courtesy of repo.or.cz).

* Git'r done!

If you like losing your time by reading stuff on how to get organized,
go and check the [[file:gitrdone.org][Git'r done!]] page..
