name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: |
          sudo add-apt-repository ppa:kelleyk/emacs
          sudo apt update --yes && sudo apt install emacs27-nox --yes
          sudo apt install graphviz --yes
          sudo apt-get install fonts-wqy-zenhei
          export GRAPHVIZ_DOT=/usr/bin/
          sudo cp ./assets/ditaa.jar /tmp/ditaa.jar
          sudo cp ./assets/plantuml.jar /tmp/plantuml.jar
          sudo chmod 777 /tmp/ditaa.jar
          sudo chmod 777 /tmp/plantuml.jar

      - name: Build the side
        run: ./build.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _site
